### ISSUE TITLE
Error in emily.js after syncing a CouchDBStore

### ISSUE THREAD

**Issue by vweyl** [flams/CouchDB-emily-tools#10]
I have come across the following error after syncing a store with a couchdb view using a reduce function:

TypeError: 'undefined' is not an object (evaluating 'destination[idx]') --> emily line 44

line 44 points to:
Tools.mixin: function mixin(source, destination, dontOverride) {
                        this.loop(source, function (value, idx) {
                                if (!destination[idx] || !dontOverride) {
                                        destination[idx] = source[idx];
                                }
                        });
                        return destination;
                }

The request
cdb.sync(db, "design", "_view/count").then(function(){
                             promise.fulfill();
                     });

The rows returned by CouchDB:
Object
rows: Array[1]
0: Object
key: null
value: 13
**proto**: Object
length: 1
**proto**: Array[0]
**proto**: Object

The design doc:
"count": {
           "map": "function(doc){if (doc.type == 7) emit(doc._id);}",
           "reduce": "_count"
       }

The Bind.plugin used in my UI:  data-count=bind:innerHTML, 0.value

Everything works fine but for this error.

**Comment by vweyl** [comment]
I got rid of the error message by adding the line
_syncInfo.query = {};
in this.setReducedViewInfo()

**Comment by podefr** [comment]
Thanks, this should be fixed in cdbtools 1.1.0
