### ISSUE TITLE
Subscribe to doc changes fails if doc is too big

### ISSUE THREAD

**Issue by vweyl** [flams/CouchDB-emily-tools#11]
If couchdb document is too large, the callback of the 'listen' requestgets fired with partial json only and fails (JSON.parse(json)).

**Comment by podefr** [comment]
Hi Vincent,

Can you confirm me that you still see the issue with CouchDB 2.0.0 as I can't seem to reproduce. I've tested with a rather large document (~4.5Mb), without any problem.
The listen request (kept alive socket) doesn't include the documents so their size shouldn't affect the request handler. Then streaming changed the document is made through another request. I've tested with everything on the same machine though, what's your set up in case you can still reproduce with latest?

Cheers
Olivier

**Comment by vweyl** [comment]
I have not seen the issue with version 2.0 -- it is not updated on the platform where I found the issue.
In the previous version the problem took place at the instruction JSON.parse of this.stopListening function, where changes was sent in multiple parts.

this.stopListening = _transport.listen(_channel, {
                                                path: "/" + _syncInfo.database + "/_changes",
                                                query: _syncInfo.query
                                        },
                                        function (changes) {
                                                var json;
                                                // Should I test for this very special case (heartbeat?)
                                                // Or do I have to try catch for any invalid json?
                                                if (changes == "\n") {
                                                        return false;
                                                }

```
                                            var json = JSON.parse(changes),
                                                    action;

                                            if (json.changes[0].rev.search("1-") == 0) {
                                                    action = "bulkAdd";
                                            } else if (json.deleted) {
                                                    action = "delete";
                                            } else {
                                                    action = "bulkChange";
                                            }

                                            _stateMachine.event(action, json.id, json.doc);


                                    }, this);
                    },
```

**Comment by podefr** [comment]
Can you tell me what's in _syncInfo.query when the bug happens?
This has changed in v2.0.0 and doesn't include the documents so is less likely to produce the bug you've described

**Comment by vweyl** [comment]
I reproduced the problem: you can see a user doc split in two parts.
I added the syncinfo.query information

Object
descending: true
feed: "continuous"
heartbeat: 20000
include_docs: true
key: ""I:1366381489496""

# **proto**: Object

# <-- couchdbtools.js:288SyntaxError: JSON Parse error: Unexpected identifier "ue" -->

Object
 "{"seq":2455,"id":"vero.patris@gmail.com","changes":[{"rev":"323-690bf578af179432663a03b2a6213be8"}],"doc":...nt":0}}

**Comment by podefr** [comment]
Fantastic, thanks for the log. And I don't think that you'll be able to reproduce the bug with the new version as the request doesn't include include_docs anymore!

I'm not closing the issue until you can confirm me that upgrading has removed the problem though
