### ISSUE TITLE
Upload function does not update _rev field in couchDBStore

### ISSUE THREAD

**Issue by vweyl** [flams/CouchDB-emily-tools#12]
Ok here's my piece of code:
console.log(CDG.get("_rev"));
CDB.upload().then(function(){
                                position = pos;
                                console.log(CDB.get("_rev"));
                                promise.fulfill();
                        });

The _rev field is the same before and after.

Adding this line in couchdbtools.js: console.log("uploading document : ", this.toJSON(), _stateMachine.getCurrent());

It turns out that the state machine is in synched state, thus calling the createDocument action instead of updateDatabase.

Adding the line this.set("_rev", json._rev) and passing the scope in the createDocument action seems to fix this issue (thus rendering the updateDatabse function redundant).

**Comment by podefr** [comment]
Hi Vincent, that's a good spot!
It's also fixed in the next version of couchdbtools, which I hope to release this weekend!

Olivier
