### ISSUE TITLE
CouchDBStore fallback to LocalStore

### ISSUE THREAD

**Issue by vweyl** [flams/CouchDB-emily-tools#5]
Offering a fallback to a LocalStore when the connection with the database is lost and automatic re-synchronization would be a great addition to this project

**Comment by podefr** [comment]
I'm reluctant to add this feature to this project, though I think that it's a great idea. 
If you think that you still have the need for this, I'd be happy to provide you with all the help that you'd need to implement it with Olives' LocalStore
