### ISSUE TITLE
Trouble removing a document from database

### ISSUE THREAD

**Issue by vweyl** [flams/CouchDB-emily-tools#9]
Use case:
-- removing a document from a list (cdbstore synchronized with a view)
1. get id of doc to be deleted (docId)
2. cdb.sync(db, docId).then(function(){
    cdb.remove();
   }

The document is not removed.
Adding console.logs and checking on the state machine it turns out that
cdb.remove() is called with proper docId but removeFromDatabase action is not triggered (as cdb is probably still in synched state, not listening).
subsequently calling _stateMachine.event("removeFromDatabase") from the console successfully deletes the document as intended.

Should the sync promise be fulfilled when store is in listening state or should remove function make sure store is in listening state?

**Comment by podefr** [comment]
fixed in 1.1.0
